baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'DaisBase'
theme = "hugo-theme-relearn-main"
prettyURLs = true
cleanUrls = true



# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]



[params]
  themeVariant = "blue"
  prettyURLs = true
  cleanUrls = true
