baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'DaisBase'
theme = "hugo-theme-relearn-main"
uglyURLs = true


# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]



[params]
  themeVariant = "blue"
  uglyURLs = true
