baseURL = 'http://www.daisbase.com/'
languageCode = 'en-us'
title = 'DaisBase'
theme = "hugo-theme-relearn-main"


# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH"]



[params]
  themeVariant = "blue"
  collapsibleMenu = true
  disableExplicitIndexURLs = true