baseURL = 'https://matt-seath.github.io/'
languageCode = 'en-AU'
title = 'Auri Finance'

[params]
  description = 'Empowering individuals on their financial journey, we are committed to making lending simple. Through personalised service and streamlined solutions, we aim to guide our clients towards financial success with ease and clarity.'
  phone = '0485 68 88 11'
  email = 'sophie@aurifinance.com.au'
  address = 'Brisbane, Queensland'
  abn = 'Auri Finance Pty Ltd ABN 27 695 121 227 is a credit representative 576761 of Finsure Finance and Insurance Pty Ltd. ABN 72 068 153 926. Australian Credit Licence Number 384704.'
  discoveryLink = 'https://app.middle.finance/ref/8e6152b2-106c-46e1-86ec-b6d1f6aa21f9'
  disclaimer = 'The information provided on this website, including articles, examples, and case studies, is for general information purposes only and does not constitute financial, credit, or legal advice. Case studies are illustrative examples based on real or typical scenarios, however individual circumstances vary and results cannot be guaranteed. The outcomes described may not be representative of all clients. Loan structures, strategies, and approvals are subject to lender assessment, eligibility criteria, and lending policies at the time of application. Before making any financial decisions, you should consider your personal objectives, financial situation, and needs, and seek appropriate professional advice where required. Auri Finance Pty Ltd acts as a mortgage broker and not a lender.'

[params.social]
  instagram = 'https://instagram.com/auri_finance'
  facebook = 'https://www.facebook.com/aurifinance'
  linkedin = 'https://www.linkedin.com/company/aurifinance'

[pagination]
  pagerSize = 9

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = 'About'
    url = '/#about'
    weight = 1
  [[menu.main]]
    name = 'Services'
    url = '/#services'
    weight = 2
  [[menu.main]]
    name = 'Process'
    url = '/#process'
    weight = 3
  [[menu.main]]
    name = 'Articles'
    url = '/articles/'
    weight = 4
